#!/usr/bin/perl
#
# Copyright (C) 2014 Modell Aachen http://modell-aachen.de
#
# For licensing info read LICENSE file in the Foswiki root.
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details, published at 
# http://www.gnu.org/copyleft/gpl.html

use strict;
use warnings;

use Getopt::Long;

my %params = ();
GetOptions (\%params, 'host=s');

# Set library paths in @INC, at compile time
BEGIN {
  $Foswiki::cfg{Engine} = 'Foswiki::Engine::CLI';
  if (-e './setlib.cfg') {
    unshift @INC, '.';
  } elsif (-e '../bin/setlib.cfg') {
    unshift @INC, '../bin';
  }
  $ENV{FOSWIKI_ACTION} = 'mailtemplatesend';
  require 'setlib.cfg';
}

use Foswiki ();
use Foswiki::UI ();

my $hostname = $params{host} || $ENV{host};
if ($hostname) {
    require Foswiki::Contrib::VirtualHostingContrib::VirtualHost;
}


if ($hostname) {
    if($hostname eq 'all') {
        Foswiki::Contrib::VirtualHostingContrib::VirtualHost->run_on_each(\&doit);
    } else {
        Foswiki::Contrib::VirtualHostingContrib::VirtualHost->run_on($hostname, \&doit);
    }
} else {
    doit();
}

sub doit {
    $Foswiki::engine->run();
}

1;
